{{- if .Values.dataService.candles.enabled }}
{{- if .Capabilities.APIVersions.Has "apps/v1beta1" }}
apiVersion: apps/v1beta1
{{- else }}
apiVersion: apps/v1
{{- end }}
kind: Deployment
metadata:
  name: candles
spec:
  minReadySeconds: 60
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: candles
  replicas: 1
  template:
    metadata:
      labels:
        app: candles
    spec:
      imagePullSecrets:
        - name: docker-registry-creds
      containers:
        - name: candles
          image: {{ .Values.dataService.candles.image }}:{{ .Values.dataService.candles.imageTag }}
          imagePullPolicy: {{ .Values.dataService.candles.imagePullPolicy }}
          env:
            - name: PGHOST
              value: {{ template "postgresHost" . }}
            - name: PGPORT
              value: {{ .Values.postgresql.service.port | quote }}
            - name: PGDATABASE
              value: {{ .Values.postgresql.postgresDatabase }}
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-creds-{{ .Release.Name }}
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds-{{ .Release.Name }}
                  key: password
            - name: CANDLES_UPDATE_INTERVAL
              value: {{ .Values.dataService.candles.updateInterval | quote }}
            - name: CANDLES_UPDATE_TIMEOUT
              value: {{ .Values.dataService.candles.updateTimeout | quote }}
            - name: RECALCULATE_ALL_CANDLES_ON_START
              value: {{ .Values.dataService.candles.recalculationOnStart | quote }}
        {{- with .Values.dataService.candles.resources }}
          resources:
{{ toYaml . | indent 12 }}
        {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
