{{- if .Capabilities.APIVersions.Has "apps/v1beta1" }}
apiVersion: apps/v1beta1
{{- else }}
apiVersion: apps/v1
{{- end }}
kind: Deployment
metadata:
  name: crawler
spec:
  minReadySeconds: 60
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: crawler
  replicas: 1
  template:
    metadata:
      labels:
        app: crawler
    spec:
      imagePullSecrets:
        - name: docker-registry-creds
      initContainers:
        - name: check-db-ready
          image: postgres:{{ .Values.postgresql.imageTag }}
          command: ['sh', '-c', 
            'until pg_isready -h {{ template "postgresqlHost" . }} -p {{ .Values.postgresql.service.port }} -U postgres;
            do echo waiting for database; sleep 2; done;']
      containers:
        - name: crawler
          image: {{ .Values.crawler.image }}:{{ .Values.crawler.imageTag }}
          imagePullPolicy: {{ .Values.crawler.imagePullPolicy }}
          env:
            - name: NODE_ADDRESS
              value: {{ .Values.crawler.nodeUrl }}
            - name: PGHOST
              value: {{ template "postgresqlHost" . }}
            - name: PGPORT
              value: {{ .Values.postgresql.service.port | quote }}
            - name: PGDATABASE
              value: {{ .Values.postgresql.postgresqlDatabase }}
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-creds-writer-{{ .Release.Name }}
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds-writer-{{ .Release.Name }}
                  key: password
            - name: BLOCKS_PER_REQUEST
              value: {{ .Values.crawler.blocksPerRequest | quote }}
            - name: ON_CONFLICT
              value: {{ .Values.crawler.onConflict }}
            - name: UPDATE_THROTTLE_INTERVAL
              value: {{ .Values.crawler.updateThrottleInterval | quote }}
            - name: MIGRATE
              value: {{ .Values.crawler.migrate | quote }}
        {{- with .Values.crawler.resources }}
          resources:
{{ toYaml . | indent 12 }}
        {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
