{{- if .Values.docs.enabled }}
{{- if .Capabilities.APIVersions.Has "apps/v1beta1" }}
apiVersion: apps/v1beta1
{{- else }}
apiVersion: apps/v1
{{- end }}
kind: Deployment
metadata:
  name: docs-cache
spec:
  minReadySeconds: 30
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: docs-cache
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/docs-cache-config-map.yaml") . | sha256sum }}
      labels:
        app: docs-cache
    spec:
      imagePullSecrets:
        - name: docker-registry-creds
      containers:
        - name: docs-cache
          image: nginx:alpine
          imagePullPolicy: Always
          volumeMounts:
            - name: docs-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          {{- with .Values.docs.cache.resources }}
{{ toYaml . | indent 10 }}
          {{- end }}
      volumes:
        - name: docs-config-volume
          configMap:
            name: docs-cache
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
