{{- if .Values.dataService.docs.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: docs-cache
  labels:
    app: docs-cache
spec:
  type: {{ .Values.dataService.docs.cache.service.type }}
  ports:
    - port: {{ .Values.dataService.docs.cache.service.port }}
      protocol: TCP
      {{- if (eq .Values.dataService.docs.cache.service.type "NodePort") }}
      nodePort: {{ .Values.dataService.docs.cache.service.nodePort }}
      {{- end }}
  selector:
    app: docs-cache
{{- end }}
