apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds-writer-{{ .Release.Name }}
data:
  username: {{ template "postgresqlWriterUser" . }}
  password: {{ template "postgresqlWriterPassword" . }}
type: Opaque
