apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds-reader-{{ .Release.Name }}
data:
  username: {{ template "postgresqlReaderUser" . }}
  password: {{ template "postgresqlReaderPassword" . }}
type: Opaque
