{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-initdb-scripts
data:
  create-user-writer.sql: {{ template "createUserWriter" . }}
  create-user-reader.sql: {{ template "createUserReader" . }}
{{- end }}    
