version: '3'
services:
  node:
    image: wavesplatform/wavesnode
    restart: always
    environment:
      WAVES_NETWORK: mainnet
      WAVES_LOG_LEVEL: INFO
      WAVES_HEAP_SIZE: 2g
      WAVES_WALLET_SEED: SEED
      WAVES_WALLET_PASSWORD: PASSWORD
      JAVA_OPTS: '-Dwaves.network.declared-address=0.0.0.0:6868 -Dwaves.rest-api.port=6870 -Dwaves.rest-api.bind-address=0.0.0.0 -Dwaves.rest-api.enable=yes'
    ports:
      - '6868:6868'
      - '6870:6870'
    volumes:
      - ./waves-data:/var/lib/waves
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blockchain
    ports:
      - '5433:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql
  crawler:
    image: wavesplatform/blockchain-postgres-sync
    restart: always
    depends_on:
      - node
      - postgres
    environment:
      NODE_ADDRESS: node:6870
      PGHOST: 'postgres'
      PGPORT: 5432
      PGDATABASE: 'blockchain'
      PGUSER: 'postgres'
      PGPASSWORD: 'postgres'
      MIGRATE: 'true'
  data-service:
    image: wavesplatform/data-service
    restart: always
    depends_on:
      - crawler
    environment:
      PORT: 3000
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: blockchain
      PGUSER: postgres
      PGPASSWORD: postgres
      PGPOOLSIZE: 20
      LOG_LEVEL: info
      DEFAULT_MATCHER: 3PJaDyprvekvPXPuAtxrapacuDJopgJRaU3
      MATCHER_SETTINGS_URL: https://matcher.wavesplatform.com/matcher/settings
    ports:
      - '3000:3000'
